config/routes.rb
Rails.application.routes.draw do
  root "google_maps#maps"

  get '/locations', to: 'google_maps#saved_locations', as: 'places'
  get '/add_location', to: 'google_maps#add_location', as: 'new_place'

  resources :distances, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/place.rb
class Place < ApplicationRecord
  # geocoded_by :address
  attr_accessor :raw_address

  geocoded_by :raw_address

  after_validation -> {
    self.address = self.raw_address
    geocode
  }, if: ->(obj){ obj.raw_address.present? and obj.raw_address != obj.address }

  after_validation :reverse_geocode, unless: ->(obj) { obj.raw_address.present? },
                 if: ->(obj){ obj.latitude.present? and obj.latitude_changed? and obj.longitude.present? and obj.longitude_changed? }

  
  reverse_geocoded_by :latitude, :longitude
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/distances_controller.rb
class DistancesController < ApplicationController
  def new
    @places = Place.all
  end

  def create
    @from = Place.find_by(id: params[:from])
    @to = Place.find_by(id: params[:to])
    if @from && @to
      flash[:success] =
          "The distance between <b>#{@from.title}</b> and <b>#{@to.title}</b> is #{@from.distance_from(@to.to_coordinates)} km"
    end
    redirect_to new_distance_path
  end
end

app/controllers/google_maps_controller.rb
# require 'googlemaps/services/places'

class GoogleMapsController < ApplicationController
  def maps
    @places = []

    total_countries = []
    total_states = []
    total_cities = []

    countries = CS.countries

    total_countries << countries.values
    total_countries.flatten!

    # countries.each do |key, value|
    #   states = CS.states(key)
    #   next if states.blank?

    #   total_states << states.values
    #   total_states.flatten!

    #   states.each do |state_code, state_value|
    #     cities = CS.cities(state_code, key)
    #     total_cities << cities

    #     next if cities.blank?

    #     total_cities.flatten!
    #   end
    # end

    @places << total_countries
    # @places << total_states
    # @places << total_cities

    @places.flatten!

    # CS.cities(state, country)
    # CS.states(country).keys.flat_map { |state| CS.cities(state, country) }

    respond_to do |format|
      format.json { render json: { places: @places } }
      format.html
    end

    filter_params = params.fetch(:filter, {})
    query_field_name = filter_params[:place]
  end

  def add_location
    @place = Place.new(place_params)

    if @place.save
      flash[:success] = "Place added!"
    end
    redirect_to root_path
  end

  def saved_locations
    @places = Place.order('created_at DESC')
  end

  def get_location
    @place = Place.find(params[:id])
  end

  private

  def place_params
    params.require(:place).permit(:title, :raw_address, :latitude, :longitude, :visited_by)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distances_helper.rb
module DistancesHelper
end

app/helpers/google_maps_helper.rb
module GoogleMapsHelper
end

app/views/distances/create.html.erb
<h1>Distances#create</h1>
<p>Find me in app/views/distances/create.html.erb</p>

app/views/distances/new.html.erb
<header><h1 class="display-4">Measure Distance</h1></header>

<%= form_tag distances_path do %>
  <fieldset class="form-group">
  <%= label_tag 'from', 'From' %>
  <%= select_tag 'from', options_from_collection_for_select(@places, :id, :title), class: "form-control" %>
</fieldset>

  <fieldset class="form-group">
  <%= label_tag 'to', 'To' %>
  <%= select_tag 'to', options_from_collection_for_select(@places, :id, :title), class: "form-control" %>
</fieldset>

  <%= submit_tag 'Go!', class: 'btn btn-primary' %>
<% end %>

app/views/google_maps/_form.html.erb
<%= form_for @place do |f| %>
  <h4>Enter either address or coordinates</h4>
  <fieldset class="form-group">
    <%= f.label :raw_address, 'Address' %>
    <%= f.text_field :raw_address, class: "form-control" %>
    <small class="text-muted">You can also enter IP. Your IP is <%= request.ip %></small>
  </fieldset>

  <div class="form-group row">
    <div class="col-sm-1">
      <%= f.label :latitude %>
    </div>
    <div class="col-sm-3">
      <%= f.text_field :latitude, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :longitude %>
    </div>
    <div class="col-sm-3">
      <%= f.text_field :longitude, class: "form-control" %>
    </div>

    <div class="col-sm-4">
      <a href="#" id="find-on-map" class="btn btn-info btn-sm">Find on the map</a>
    </div>
  </div>

  <div class="card">
    <div class="card-block">
      <div id="map"></div>
    </div>
  </div>
  <%= f.submit 'Add!', class: 'btn btn-primary' %>
<% end %>

app/views/google_maps/_place.html.erb
<li>
  <%= link_to place.title, place_path(place) %>
  visited by <strong><%= place.visited_by %></strong>
</li>

app/views/google_maps/add_location.html.erb
<header><h1 class="display-4">Add Place</h1></header>

<%= render 'form' %>

app/views/google_maps/get_location.html.erb
<header><h1 class="display-4"><%= @place.title %></h1></header>

<p>Address: <%= @place.address %></p>
<p>Coordinates: <%= @place.latitude %> <%= @place.longitude %></p>

<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@place.latitude},#{@place.longitude}&markers=#{@place.latitude},#{@place.longitude}&zoom=7&size=640x400&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8", class: 'img-fluid img-rounded', alt: "#{@place.title} on the map"%>

app/views/google_maps/maps.html.erb
<div id='main'>
  <div id="search-bar">
    <div class="row">
      <div class="col-12">
        <div class="card mb-30">
          <div class="card-body table-responsive">
            <%= form_tag root_path, method: :get do %>
              <div class="row">
                <% selected_field_option = params.fetch(:filter, {})[:place] %>
                <%= select_tag 'filter[place]', options_for_select(@countries.values, selected_field_option), include_blank: '--Select a place--', class: 'form-control', id: 'select-place', required: true %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="map"></div>
</div>

<!-- <script type="text/javascript">
  $("#select-place").on('change', function(){
    $.ajax({
      url: '/',
      method: 'GET',
      data: {
        place_name: $(this).val()
      },
      success: function(data) {
        alert('successfully');
        console.log("Countries", data);
      }
    })
    console.log("changin", $(this).val());
  })
</script> -->

app/views/google_maps/saved_locations.html.erb
<header><h1 class="display-4">Location</h1></header>

<%= link_to 'Add place', new_place_path, class: 'btn btn-primary btn-lg' %>

<div class="card">
  <div class="card-block">
    <ul>
      <%= render @places %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGoogleMaps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag 'jquery.min', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'map' %>
    <!-- <%= javascript_importmap_tags %> -->
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg.html_safe, class: "alert alert-#{name}") %>
    <% end %>
    <%= yield %>
    <script async defer 
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYgz93to_KfefAj2f2T85hwqVdPWgr1m0&callback=initMap&libraries=places,drawing,geometry">
    </script>
  </body>
</html>